name: Production Deployment (S3 bucket and invalidate CDN cache)
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.3.0]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v3
        - name: Use node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Install dependencies
          run: yarn install
        - name: Build
          run: yarn build-prod
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: dist
            bucket-region: us-east-1
            # deployment is set up in the aws-infra repo, you'll wanna get these values from cloudformation
            bucket: alexpereira.dev-production
            dist-id: E2IAE8HML09QZ7
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"
